package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import java.util.Optional;
import java.util.function.Supplier;

import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;

import choreo.trajectory.SwerveSample;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.controller.PIDController;
import edu.wpi.first.math.filter.Debouncer.DebounceType;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.button.Trigger;
import frc.robot.generated.TunerConstantsArkelon0416.TunerSwerveDrivetrain;

import static frc.robot.Utils.is_between;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class Drivetrain extends TunerSwerveDrivetrain implements Subsystem {
    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;

    private final PIDController xController = new PIDController(7.0, 0.0, 0.0);
    private final PIDController yController = new PIDController(7.0, 0.0, 0.0);
    private final PIDController headingController = new PIDController(8.5, 0.0, 0.0);

    private final PIDController trajectoryxController = new PIDController(1, 0.0, 0.0);
    private final PIDController trajectoryyController = new PIDController(1, 0.0, 0.0);
    private final PIDController trajectoryheadingController = new PIDController(0.5, 0.0, 0);

    public Supplier<Pose2d> poseSetpoint = () -> new Pose2d();

    public Trigger isAtPoseSetpoint = new Trigger(() -> isAtPoseSetpoint(false));
    public Trigger iapsDebounce2 = new Trigger(() -> isAtPoseSetpointVariable(false, 40, 12))
        .debounce(0.5, DebounceType.kBoth);

    public Trigger isAtPoseSetpointDebounce = new Trigger(() -> isAtPoseSetpoint(false))
        .debounce(0.5);

    public Trigger isAtPoseSetpointDebounceExcludeTranslation = new Trigger(() -> isAtPoseSetpoint(true))
        .debounce(0.5);

    public double speedMultiplier = 1;

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants   Drivetrain-wide constants for the swerve drive
     * @param modules               Constants for each specific module
     */
    public Drivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If
     *                                unspecified or set to 0 Hz, this is 250 Hz on
     *                                CAN FD, and 100 Hz on CAN 2.0.
     * @param modules                 Constants for each specific module
     */
    public Drivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    public Drivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        Matrix<N3, N1> odometryStandardDeviation,
        Matrix<N3, N1> visionStandardDeviation,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * Returns a command that applies the specified control request to this swerve drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    @Override
    public void periodic() {
        headingController.enableContinuousInput(-Math.PI+0.000000000000001, Math.PI);
        trajectoryheadingController.enableContinuousInput(-Math.PI+0.000000000000001, Math.PI);
        // SmartDashboard.putNumber("isAlignedWhenTurning", isAtPoseSetpointDebounceExcludeTranslation.getAsBoolean() ? 2000 : 0);
        SmartDashboard.putNumber("isAlignedWhenTurning", iapsDebounce2.getAsBoolean() ? 2000 : 0);
        
        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is disabled.
         * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
         */
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
                DriverStation.getAlliance().ifPresent(allianceColor -> {
                    SmartDashboard.putString("Color :)", allianceColor.toString());
                    setOperatorPerspectiveForward(
                        allianceColor == Alliance.Red
                            ? kRedAlliancePerspectiveRotation
                            : kBlueAlliancePerspectiveRotation
                    );
                    m_hasAppliedOperatorPerspective = true;
                }
            );
        }
    }

    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement
     *     in the form [x, y, theta]ᵀ, with units in meters and radians.
     */
    @Override
    public void addVisionMeasurement(
        Pose2d visionRobotPoseMeters,
        double timestampSeconds,
        Matrix<N3, N1> visionMeasurementStdDevs
    ) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }

    public Pose2d getPos() {
        return getState().Pose;
    }

    public void followTrajectory(SwerveSample sample) {
        // Get the current pose of the robot
        Pose2d pose = getState().Pose;

        // Generate the next speeds for the robot
        ChassisSpeeds speeds = new ChassisSpeeds(
                sample.vx + trajectoryxController.calculate(pose.getX(), sample.x),
                sample.vy + trajectoryyController.calculate(pose.getY(), sample.y),
                sample.omega + trajectoryheadingController.calculate(pose.getRotation().getRadians(), sample.heading)
        );


        // Apply the generated speeds
        setControl(new SwerveRequest.ApplyFieldSpeeds().withSpeeds(speeds));
    }

    public boolean isAtPoseSetpoint(boolean excludeTranslation) {
        Pose2d relativepose = poseSetpoint.get().relativeTo(getPos());
        boolean angleInRange = is_between(
            getPos().getRotation().getDegrees(),
            poseSetpoint.get().getRotation().getDegrees()+2.5,
            poseSetpoint.get().getRotation().getDegrees()-2.5
        );
        boolean isAtPose = 
                Math.abs(relativepose.getX()) < Inches.of(3.5).in(Meters) && 
                Math.abs(relativepose.getY()) < Inches.of(3.5).in(Meters) &&
                angleInRange;

        return excludeTranslation ? angleInRange : isAtPose;
    }

    public boolean isAtPoseSetpointVariable(boolean excludeTranslation,
        double angleToleranceInches,
        double positionTolerance
    ) {
        Pose2d relativepose = poseSetpoint.get().relativeTo(getPos());
        boolean angleInRange = is_between(
            getPos().getRotation().getDegrees(),
            poseSetpoint.get().getRotation().getDegrees()+angleToleranceInches,
            poseSetpoint.get().getRotation().getDegrees()-angleToleranceInches
        );
        boolean isAtPose = 
                Math.abs(relativepose.getX()) < Inches.of(positionTolerance).in(Meters) && 
                Math.abs(relativepose.getY()) < Inches.of(positionTolerance).in(Meters) &&
                angleInRange;

        return excludeTranslation ? angleInRange : isAtPose;
    }

    public void goToPose() {
        // Get the current pose of the robot
        Pose2d pose = getPos();

        // Generate the next speeds for the robot
        ChassisSpeeds speeds = new ChassisSpeeds(
            xController.calculate(pose.getX(), poseSetpoint.get().getX())*speedMultiplier,
            yController.calculate(pose.getY(), poseSetpoint.get().getY())*speedMultiplier,
            headingController.calculate(pose.getRotation().getRadians(), poseSetpoint.get().getRotation().getRadians())*speedMultiplier
        );

        // Apply the generated speeds
        setControl(new SwerveRequest.ApplyFieldSpeeds().withSpeeds(speeds));
    }

    public void turnToPose() {
        // Get the current pose of the robot
        Pose2d pose = getPos();

        // Generate the next speeds for the robot
        ChassisSpeeds speeds = new ChassisSpeeds(
            // xController.calculate(pose.getX(), poseSetpoint.get().getX()),
            // yController.calculate(pose.getY(), poseSetpoint.get().getY()),
            0,0,
            headingController.calculate(pose.getRotation().getRadians(), poseSetpoint.get().getRotation().getRadians())
        );

        // Apply the generated speeds
        setControl(new SwerveRequest.ApplyFieldSpeeds().withSpeeds(speeds));
    }

    public void turnToPoseOTM(Supplier<Double> xspeed, Supplier<Double> yspeed) {
        // Get the current pose of the robot
        Pose2d pose = getPos();

        // Generate the next speeds for the robot
        ChassisSpeeds speeds = new ChassisSpeeds(
            xspeed.get(), yspeed.get(),
            headingController.calculate(pose.getRotation().getRadians(), poseSetpoint.get().getRotation().getRadians())
        );

        // Apply the generated speeds
        setControl(new SwerveRequest.ApplyFieldSpeeds().withSpeeds(speeds));
    }

    public Command goToPoseCommand() {
        return Commands.parallel(
                run(() -> goToPose())
            )
            .finallyDo(() -> setControl(new SwerveRequest.Idle()))
            ;
    }

    public Command goToPoseCommand(Supplier<Pose2d> newPose) {
        return runOnce(() -> poseSetpoint = newPose).andThen(goToPoseCommand());
    }

    public Command goToPoseCommandStatic(Supplier<Pose2d> newPose) {
        return runOnce(() -> poseSetpoint = () -> newPose.get()).andThen(goToPoseCommand());
    }

    public Command pointAtPose(Supplier<Pose2d> target) {
        return run(() -> {
            Pose2d currentPose = getPos();
            poseSetpoint = () -> new Pose2d(
                currentPose.getX(),
                currentPose.getY(),
                Rotation2d.fromRadians(
                    Math.atan2(
                        target.get().getY()-currentPose.getY(),
                        target.get().getX()-currentPose.getX()
                    )
                )
            );
        }).alongWith(Commands.run(() -> turnToPose()));
    }

    public Command pointAtPose(Supplier<Pose2d> target, Supplier<Double> xspeed, Supplier<Double> yspeed) {
        return run(() -> {
            Pose2d currentPose = getPos();
            poseSetpoint = () -> new Pose2d(
                currentPose.getX(),
                currentPose.getY(),
                Rotation2d.fromRadians(
                    Math.atan2(
                        target.get().getY()-currentPose.getY(),
                        target.get().getX()-currentPose.getX()
                    )
                )
            );
        }).alongWith(Commands.run(() -> turnToPoseOTM(xspeed, yspeed)));
    }
}